### ISSUE TITLE
Show user warning if filetype is not supported during tour upload

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#25]
```
./trekview.py createtour /Users/davidgreenwood/Downloads/UKFP003
Directory: /Users/davidgreenwood/Downloads/UKFP003
Do you agree to Google’s Terms of Service? https://policies.google.com/terms [y/N]: y
Validating files before upload
Do you want to connect photos in ascending time order (recommended) [T], ascending alphabetical order [A], or no connection to be made [N]? If no selected, Google will automatically attempt to link your photos if they are no more than 5 meters apart: t
Do you want to Tourer to calculate photo heading (direction)? This is recommended if the connected photos have a clear line of sight between them. [Y]/N [Y]: y
Traceback (most recent call last):
  File "./trekview.py", line 896, in <module>
    cli()
  File "/Users/davidgreenwood/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/davidgreenwood/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/davidgreenwood/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/davidgreenwood/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/davidgreenwood/.pyenv/versions/3.6.5/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./trekview.py", line 893, in createtour
    upload_files(path)
  File "./trekview.py", line 315, in upload_files
    valid_file = validate_file(f)
  File "./trekview.py", line 120, in validate_file
    img = Image.open(fpath)
  File "/Users/davidgreenwood/.pyenv/versions/3.6.5/lib/python3.6/site-packages/PIL/Image.py", line 2822, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file '/Users/davidgreenwood/Downloads/UKFP003/Icon\r'
```

After validation step, upload fails. It looks like items with no filetype are skipped during check and cause issue at upload.

**Comment by annndrey** [comment]
Fixed in 8694edc39fb5447c8b195f00a1861280ecf11997
